name: check-run-test
on:
  check_run:
    types: [rerequested, requested_action]
    
jobs:
  check-run-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - name: Show Information
      run: |
        echo "This workflow run is triggered by ${{ github.event_name }} "
        echo " *****************************************************************************"
        echo "$GITHUB_CONTEXT"
        echo " *****************************************************************************"