name: learn-github-actions
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      run: |
        echo Hello world $FIRST_NAME $middle_name $Last_Name!
        echo "Hello ${{ github.event_name }}!"
      env:
        FIRST_NAME: Mona
        middle_name: The
        Last_Name: Octocat
    - name: Try Calling Separate Action
      uses: ./.github/workflows
      with:
        name: "Roberto!"