name: learn-github-actions
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      run: echo Hello world $FIRST_NAME $middle_name $Last_Name!
      run: echo "Hello ${{ github.event }}!"
      env:
        FIRST_NAME: Mona
        middle_name: The
        Last_Name: Octocat