name: learn-github-actions
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world
      run: |
        echo Hello world $FIRST_NAME $middle_name $Last_Name!
        echo "Hello ${{ github.event_name }}!"
      env:
        FIRST_NAME: Mona
        middle_name: The
        Last_Name: Octocat
    - uses: actions/checkout@v1
    - id: auth
      uses: jnwng/github-app-installation-token-action@v1
      with:
        appId: ${{ secrets.GITHUB_APP_ID }}
        installationId: ${{ secrets.GITHUB_APP_INSTALLATION_ID }}
        privateKey: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
    - name: Try???
      uses: ./.github/actions/action
      with:
        name: ${{ secrets.NAME }}
        GITHUB_TOKEN: ${{ steps.installationToken.outputs.token }}