name: codeowners-generate-auto-check
on: [push]
    
jobs:
  trigger-codeowners-generate-auto_2:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
    - name: Show Information
      run: |
        echo "This workflow run is triggered by ${{ github.event_name }} ."
        echo " *****************************************************************************"
        echo "$GITHUB_CONTEXT"
        echo " *****************************************************************************"
    # - name: Hello world
    #   run: |
    #     echo Hello world $FIRST_NAME $middle_name $Last_Name!
    #     echo "Hello ${{ github.event_name }}!"
    #   env:
    #     FIRST_NAME: Mona
    #     middle_name: The
    #     Last_Name: Octocat
    # - uses: actions/checkout@v1
    # - id: auth
    #   uses: jnwng/github-app-installation-token-action@v1
    #   with:
    #     appId: ${{ secrets.APP_ID }}
    #     installationId: ${{ secrets.APP_INSTALLATION_ID }}
    #     privateKey: ${{ secrets.APP_PRIVATE_KEY }}
    # - name: Try???
    #   uses: ./.github/actions/action
    #   with:
    #     name: ${{ secrets.NAME }}
    #     APP_ID: ${{ secrets.APP_ID }}
    #     INSTALLATION_ID:  ${{ secrets.APP_INSTALLATION_ID }}
    #     GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
    #     action: "CREATE_CHECK"
    # - name: Trigger status event
    #     run: >-
    #       curl -L -X POST 
    #       -H "Content-Type: application/json"
    #       -H "Authorization: token ${{ steps.auth.outputs.token }}"
    #       -d '{
    #         "state": "pending",
    #         "target_url": "https://you-can-add-a.url/",
    #         "description": "All tests passed", "context": "your-custom/status-event"
    #       }'
    #       "https://api.github.com/repos/${{ github.repository.name }}/statuses/${{ github.sha }}"